"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { updateLandingTemplateAction } from "@/app/dashboard/actions";

export interface TemplateItem {
  id: string;
  name: string;
  slug: string;
  preview_image_url: string | null;
}

// Same static preview thumbnails OnboardingWizard.tsx uses (most are
// generated by `npm run generate:previews` -- see that file's comment).
// Templates without an entry here fall back to the DB's generic
// placehold.co image.
const TEMPLATE_PREVIEW_IMAGE: Record<string, string> = {
  "contadores:moderno": "/previews/contador-moderno.jpg",
  "contadores:clasico": "/previews/contador-clasico.jpg",
  "contadores:minimal": "/previews/contador-minimal.jpg",
  "abogados:moderno": "/previews/abogado-moderno.jpg",
  "abogados:clasico": "/previews/abogado-clasico.jpg",
  "abogados:minimal": "/previews/abogado-minimal.jpg",
};

export function TemplateGallery({
  landingId,
  professionSlug,
  templates,
  currentTemplateId,
}: {
  landingId: string;
  professionSlug: string;
  templates: TemplateItem[];
  currentTemplateId: string;
}) {
  const router = useRouter();
  const [pendingTemplate, setPendingTemplate] = useState<TemplateItem | null>(null);
  const [isPending, startTransition] = useTransition();
  const [error, setError] = useState<string | null>(null);

  function confirmChange() {
    if (!pendingTemplate) return;
    setError(null);
    startTransition(async () => {
      const result = await updateLandingTemplateAction(landingId, pendingTemplate.id);
      if (!result.ok) {
        setError("No se pudo cambiar la plantilla. Intentá de nuevo.");
        return;
      }
      router.push("/dashboard?plantilla=1");
    });
  }

  return (
    <>
      <div className="grid grid-cols-1 gap-5 sm:grid-cols-3">
        {templates.map((t) => {
          const isCurrent = t.id === currentTemplateId;
          const previewImage =
            TEMPLATE_PREVIEW_IMAGE[`${professionSlug}:${t.slug}`] ?? t.preview_image_url;

          return (
            <button
              key={t.id}
              type="button"
              disabled={isCurrent}
              onClick={() => setPendingTemplate(t)}
              className={`group flex flex-col overflow-hidden rounded-2xl bg-white text-left transition-all duration-200 ${
                isCurrent
                  ? "cursor-default ring-[3px] ring-sky shadow-lg shadow-sky/20"
                  : "ring-1 ring-black/8 hover:-translate-y-1 hover:shadow-md hover:ring-black/15"
              }`}
            >
              <div className="relative w-full overflow-hidden bg-surface-muted">
                {previewImage ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={previewImage}
                    alt={`Vista previa del diseño ${t.name}`}
                    className="block h-auto w-full"
                  />
                ) : (
                  <div className="flex h-48 items-center justify-center text-sm font-medium text-gray-400">
                    {t.name}
                  </div>
                )}
                {isCurrent && (
                  <span className="absolute left-3 top-3 rounded-full bg-sky px-3 py-1 text-xs font-semibold text-white shadow-md">
                    Plantilla actual
                  </span>
                )}
              </div>
              <div className="flex items-center justify-between px-4 py-3">
                <span className="text-sm font-semibold text-navy">{t.name}</span>
                {!isCurrent && (
                  <span className="text-xs font-medium text-sky opacity-0 transition-opacity group-hover:opacity-100">
                    Elegir →
                  </span>
                )}
              </div>
            </button>
          );
        })}
      </div>

      {pendingTemplate && (
        <div
          className="fixed inset-0 z-[70] flex items-center justify-center bg-navy/40 px-4"
          role="dialog"
          aria-modal="true"
          aria-labelledby="change-template-title"
        >
          <div className="w-full max-w-sm rounded-2xl bg-white p-6 shadow-xl">
            <h2 id="change-template-title" className="text-lg font-semibold text-navy">
              ¿Querés cambiar a esta plantilla?
            </h2>
            <p className="mt-2 text-sm text-text-body">
              Tu contenido (textos, foto, datos) se mantendrá, solo cambia el
              diseño visual.
            </p>

            {error && <p className="mt-3 text-sm text-red-600">{error}</p>}

            <div className="mt-5 flex flex-col gap-2">
              <button
                type="button"
                onClick={confirmChange}
                disabled={isPending}
                className="inline-flex min-h-11 items-center justify-center rounded-full bg-sky px-5 text-sm font-semibold text-white transition-colors hover:bg-sky-dark disabled:opacity-50"
              >
                {isPending ? "Cambiando..." : `Cambiar a ${pendingTemplate.name}`}
              </button>
              <button
                type="button"
                onClick={() => setPendingTemplate(null)}
                disabled={isPending}
                className="inline-flex min-h-11 items-center justify-center rounded-full border border-border-subtle px-5 text-sm font-medium text-navy transition-colors hover:border-navy/40"
              >
                Cancelar
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
