"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import type { FormSchema } from "@/lib/forms/validate-form-data";
import { ROOT_DOMAIN } from "@/lib/root-domain";
import { FieldInput } from "@/components/forms/FieldInput";
import { Wordmark } from "@/components/landing/Wordmark";
import { checkSlugAvailabilityAction, createLandingAction } from "./actions";
import { ContadorWizard } from "./ContadorWizard";
import { AbogadoWizard } from "./AbogadoWizard";
import { PsicologoWizard } from "./PsicologoWizard";
import { PRIMARY_BUTTON, SECONDARY_BUTTON } from "./styles";

export interface Profession {
  id: string;
  name: string;
  slug: string;
  form_schema: FormSchema;
}

export interface Template {
  id: string;
  profession_id: string;
  name: string;
  slug: string;
  preview_image_url: string | null;
  config: {
    primaryColor?: string;
    secondaryColor?: string;
    layout?: string;
  } | null;
}

export interface StockImage {
  id: string;
  category: string;
  image_url: string;
}

type Step = "profession" | "template" | "form" | "slug";

type SlugStatus =
  | { state: "checking" }
  | { state: "available" }
  | { state: "taken"; suggestions: string[] }
  | { state: "invalid"; message: string };

// Professions with a dedicated, richer wizard (own steps + live preview)
// instead of the generic form_schema-driven fallback below. The grid in
// the "profession" step still renders every row from the DB; the branch
// right below this set picks which wizard component to render for each.
const DEDICATED_WIZARD_PROFESSIONS = new Set(["contadores", "abogados", "psicologos"]);

// Static preview thumbnails for the templates that were ported to React.
// Most are generated by `npm run generate:previews`
// (scripts/generate-previews.js), which fills each template's
// {{placeholders}} with fictional sample data, renders it with Playwright,
// and writes a JPEG (public/previews/) shown as the full card image below.
// The contador clasico/minimal ones and all three psicologo ones were
// instead captured directly from the real component render (Playwright
// screenshotting the actual template component with sample data via a real
// `next dev`, see scripts/generate-component-previews.js and
// src/app/dev-preview/psicologo/) since neither has a separate static-HTML
// source under /templates/. Templates without an entry here fall back to a
// plain name-only card.
const TEMPLATE_PREVIEW_IMAGE: Record<string, string> = {
  "contadores:moderno": "/previews/contador-moderno.jpg",
  "contadores:clasico": "/previews/contador-clasico.jpg",
  "contadores:minimal": "/previews/contador-minimal.jpg",
  "abogados:moderno": "/previews/abogado-moderno.jpg",
  "abogados:clasico": "/previews/abogado-clasico.jpg",
  "abogados:minimal": "/previews/abogado-minimal.jpg",
  "psicologos:moderno": "/previews/psicologo-moderno.jpg",
  "psicologos:clasico": "/previews/psicologo-clasico.jpg",
  "psicologos:minimal": "/previews/psicologo-minimal.jpg",
};

// For the "profession" step card, one representative screenshot per
// profession (its flagship "Moderno" template) rather than a generic
// icon -- reuses the same real Playwright-rendered images above instead
// of a placeholder gradient, for the professions that have one.
const PROFESSION_PREVIEW_IMAGE: Record<string, string> = {
  contadores: "/previews/contador-moderno.jpg",
  abogados: "/previews/abogado-moderno.jpg",
  psicologos: "/previews/psicologo-moderno.jpg",
};

// Fallback for a profession with no rendered preview yet.
const PROFESSION_GRADIENT: Record<string, string> = {
  contadores: "linear-gradient(135deg, #1b4f72, #1b4f72)",
  abogados: "linear-gradient(135deg, #1a2744, #c9a84c)",
  psicologos: "linear-gradient(135deg, #5b6b8c, #6b7f6b)",
};

const PROFESSION_SUBTITLE: Record<string, string> = {
  contadores: "Impuestos · Liquidaciones · Asesoramiento",
  abogados: "Derecho Civil · Familia · Societario · Laboral",
  psicologos: "Clínica · Infanto-juvenil · Organizacional",
};

export function OnboardingWizard({
  professions,
  templates,
  stockImages,
  isAuthenticated,
}: {
  professions: Profession[];
  templates: Template[];
  stockImages: StockImage[];
  isAuthenticated: boolean;
}) {
  const router = useRouter();
  const [step, setStep] = useState<Step>("profession");
  const [professionId, setProfessionId] = useState<string | null>(null);
  const [templateId, setTemplateId] = useState<string | null>(null);
  const [previewTemplate, setPreviewTemplate] = useState<Template | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});
  const [imageMode, setImageMode] = useState<"stock" | "manual">("stock");
  const [slugInput, setSlugInput] = useState("");
  const [slugStatus, setSlugStatus] = useState<SlugStatus | null>(null);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const profession = professions.find((p) => p.id === professionId) ?? null;
  const professionTemplates = useMemo(
    () => templates.filter((t) => t.profession_id === professionId),
    [templates, professionId]
  );
  const selectedTemplate =
    professionTemplates.find((t) => t.id === templateId) ?? null;
  const usesDedicatedWizard = Boolean(
    profession && DEDICATED_WIZARD_PROFESSIONS.has(profession.slug)
  );

  useEffect(() => {
    if (step !== "slug" || slugInput.trim().length === 0) {
      return;
    }
    const handle = setTimeout(async () => {
      setSlugStatus({ state: "checking" });
      const result = await checkSlugAvailabilityAction(slugInput);
      if (!result.valid) {
        setSlugStatus({ state: "invalid", message: result.message });
      } else if (result.available) {
        setSlugStatus({ state: "available" });
      } else {
        setSlugStatus({ state: "taken", suggestions: result.suggestions });
      }
    }, 500);
    return () => clearTimeout(handle);
  }, [slugInput, step]);

  function updateValue(key: string, value: string) {
    setValues((v) => ({ ...v, [key]: value }));
  }

  function handleSubmit() {
    if (!professionId || !templateId) return;
    setSubmitError(null);
    setFormErrors({});
    startTransition(async () => {
      const result = await createLandingAction({
        professionId,
        templateId,
        formData: values,
        desiredSlug: slugInput,
      });

      if (result.ok) {
        router.push("/dashboard");
        return;
      }

      switch (result.reason) {
        case "invalid_form_data":
          setFormErrors(result.errors);
          setStep("form");
          break;
        case "slug_taken":
          setSlugStatus({ state: "taken", suggestions: result.suggestions });
          break;
        case "invalid_slug":
          setSlugStatus({ state: "invalid", message: result.message });
          break;
        case "already_has_landing":
          router.push("/dashboard");
          break;
        default:
          setSubmitError("No se pudo crear la landing. Intentá de nuevo.");
      }
    });
  }

  return (
    <div className="flex min-h-full flex-1 flex-col bg-[#f8fafc]">
      <WizardHeader />

      {step === "form" && profession && usesDedicatedWizard && selectedTemplate ? (
        profession.slug === "abogados" ? (
          <AbogadoWizard
            profession={profession}
            template={selectedTemplate}
            stockImages={stockImages}
            isAuthenticated={isAuthenticated}
            onBack={() => setStep("template")}
          />
        ) : profession.slug === "psicologos" ? (
          <PsicologoWizard
            profession={profession}
            template={selectedTemplate}
            stockImages={stockImages}
            isAuthenticated={isAuthenticated}
            onBack={() => setStep("template")}
          />
        ) : (
          <ContadorWizard
            profession={profession}
            template={selectedTemplate}
            stockImages={stockImages}
            isAuthenticated={isAuthenticated}
            onBack={() => setStep("template")}
          />
        )
      ) : (
        <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-8 px-5 py-6 sm:gap-16 sm:px-8 sm:py-16">
          <div className="sticky top-14 z-20 -mx-5 bg-[#f8fafc]/95 px-5 pt-1 pb-3 backdrop-blur sm:static sm:mx-0 sm:bg-transparent sm:px-0 sm:py-0 sm:backdrop-blur-none">
            <Steps current={step} />
          </div>

          {step === "profession" && (
            <section className="flex flex-col gap-6 sm:gap-8">
              <div className="flex flex-col gap-2">
                <h2 className="text-2xl font-bold text-navy sm:text-3xl">
                  Elegí tu profesión
                </h2>
                <p className="text-base text-gray-600">
                  Seleccioná tu área profesional para ver las plantillas
                  disponibles.
                </p>
              </div>

              <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 sm:gap-6">
                {professions.map((p) => {
                  const previewImage = PROFESSION_PREVIEW_IMAGE[p.slug];
                  const gradient =
                    PROFESSION_GRADIENT[p.slug] ??
                    "linear-gradient(135deg, #0f1f3d, #334155)";
                  const subtitle =
                    PROFESSION_SUBTITLE[p.slug] ??
                    "Plantillas profesionales listas para usar";

                  return (
                    <button
                      key={p.id}
                      onClick={() => {
                        setProfessionId(p.id);
                        setTemplateId(null);
                        setStep("template");
                      }}
                      className={`group relative flex flex-col overflow-hidden rounded-2xl bg-white text-left shadow-sm ring-1 ring-black/5 transition-all duration-200 hover:-translate-y-1 hover:shadow-lg ${
                        professions.length % 3 === 1 &&
                        professions.indexOf(p) === professions.length - 1
                          ? "col-span-2 sm:col-span-1"
                          : ""
                      }`}
                    >
                      {/* imagen: compacta en mobile, 220px desde sm */}
                      <div className="relative h-24 w-full shrink-0 overflow-hidden sm:h-[220px]">
                        {previewImage ? (
                          <Image
                            src={previewImage}
                            alt={`Vista previa de páginas de ${p.name}`}
                            fill
                            sizes="(min-width: 640px) 33vw, 50vw"
                            className="object-cover object-top"
                          />
                        ) : (
                          <div
                            className="flex h-full w-full items-center justify-center"
                            style={{ background: gradient }}
                          >
                            <span className="px-2 text-center text-xs font-medium text-white/90 sm:text-sm">
                              Moderno · Clásico · Minimal
                            </span>
                          </div>
                        )}
                      </div>

                      {/* info — altura fija para que todas las cards sean iguales */}
                      <div className="flex flex-col justify-center gap-1 px-3 py-3 sm:min-h-[88px] sm:px-5 sm:py-4">
                        <span className="text-sm font-semibold text-gray-900 leading-snug sm:text-lg">
                          {p.name}
                        </span>
                        <span className="hidden text-xs text-gray-500 leading-relaxed sm:block">
                          {subtitle}
                        </span>
                      </div>

                      <div className="pointer-events-none absolute inset-x-0 bottom-0 hidden h-11 items-center justify-center bg-navy text-sm font-medium text-white opacity-0 transition-opacity duration-200 group-hover:opacity-100 sm:flex">
                        Comenzar →
                      </div>
                    </button>
                  );
                })}

              </div>

              <Link
                href="/"
                className="pt-2 text-center text-sm text-sky hover:underline"
              >
                ← Volver al inicio
              </Link>
            </section>
          )}

          {step === "template" && profession && (
            <section className="flex flex-col gap-6 sm:gap-8">
              <div className="flex flex-col gap-1">
                <h2 className="text-2xl font-bold text-navy sm:text-3xl">Elegí tu diseño</h2>
                <p className="text-base text-gray-600">
                  Todos los diseños incluyen las mismas secciones. Podés cambiar el estilo después.
                </p>
              </div>

              <div className="-mx-5 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 pb-2 sm:mx-0 sm:grid sm:grid-cols-3 sm:gap-6 sm:overflow-visible sm:px-0 sm:pb-0">
                {professionTemplates.map((t) => (
                  <div key={t.id} className="w-[72vw] shrink-0 snap-center sm:w-auto">
                    <TemplateCard
                      template={t}
                      professionSlug={profession.slug}
                      selected={templateId === t.id}
                      onSelect={() => {
                        setTemplateId(t.id);
                        setStep("form");
                      }}
                      onPreview={() => setPreviewTemplate(t)}
                    />
                  </div>
                ))}
              </div>

              <button
                onClick={() => setStep("profession")}
                className="self-start text-sm text-gray-500 hover:text-navy hover:underline"
              >
                ← Volver a profesiones
              </button>
            </section>
          )}

          {step === "form" && profession && (
            <section className="flex flex-col gap-4">
              <h2 className="text-xl font-semibold text-navy">
                Completá tus datos
              </h2>
              {profession.form_schema.fields.map((field) => (
                <FieldInput
                  key={field.key}
                  field={field}
                  value={values[field.key] ?? ""}
                  error={formErrors[field.key]}
                  onChange={(v) =>
                    updateValue(field.key, typeof v === "string" ? v : "")
                  }
                  imageMode={imageMode}
                  onImageModeChange={setImageMode}
                  stockImages={stockImages}
                />
              ))}
              {formErrors._form && (
                <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">
                  {formErrors._form}
                </p>
              )}
              <div className="h-20 sm:hidden" aria-hidden />
              <div className="fixed inset-x-0 bottom-0 z-30 flex gap-3 border-t border-border-subtle bg-white/95 px-5 py-3 backdrop-blur sm:static sm:z-auto sm:border-0 sm:bg-transparent sm:px-0 sm:py-0 sm:backdrop-blur-none">
                <button onClick={() => setStep("template")} className={SECONDARY_BUTTON}>
                  Volver
                </button>
                <button onClick={() => setStep("slug")} className={`${PRIMARY_BUTTON} flex-1 sm:flex-none`}>
                  Continuar
                </button>
              </div>
            </section>
          )}

          {step === "slug" && (
            <section className="flex flex-col gap-4">
              <h2 className="text-xl font-semibold text-navy">
                Elegí tu subdominio
              </h2>
              <div className="flex items-center gap-2">
                <input
                  value={slugInput}
                  onChange={(e) => setSlugInput(e.target.value)}
                  placeholder="ej: contadorjuanperez"
                  className="min-h-12 flex-1 rounded-lg border border-border-subtle bg-white px-3 py-2 text-navy focus:border-sky focus:outline-none focus:ring-2 focus:ring-sky/30"
                />
                <span className="text-sm text-text-body">.{ROOT_DOMAIN}</span>
              </div>

              {slugStatus && (
                <SlugFeedback status={slugStatus} onPick={setSlugInput} />
              )}

              {submitError && (
                <p className="rounded-lg border border-red-200 bg-red-50 px-3 py-2 text-sm font-medium text-red-700">
                  {submitError}
                </p>
              )}

              <div className="h-20 sm:hidden" aria-hidden />
              <div className="fixed inset-x-0 bottom-0 z-30 flex gap-3 border-t border-border-subtle bg-white/95 px-5 py-3 backdrop-blur sm:static sm:z-auto sm:border-0 sm:bg-transparent sm:px-0 sm:py-0 sm:backdrop-blur-none">
                <button onClick={() => setStep("form")} className={SECONDARY_BUTTON}>
                  Volver
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={isPending || slugStatus?.state !== "available"}
                  className={`${PRIMARY_BUTTON} flex-1 sm:flex-none`}
                >
                  {isPending ? "Creando..." : "Crear landing"}
                </button>
              </div>
            </section>
          )}
        </div>
      )}
      <footer className="mt-auto border-t border-gray-100 px-5 py-5 text-center text-xs text-gray-500 sm:px-6">
        <span>© {new Date().getFullYear()} weboficial</span>
        {" · "}
        <a href="/terminos" className="hover:text-gray-600 hover:underline">Términos</a>
        {" · "}
        <a href="/privacidad" className="hover:text-gray-600 hover:underline">Privacidad</a>
        {" · "}
        <a href="mailto:ideasdigitalesml@gmail.com" className="hover:text-gray-600 hover:underline">Contacto</a>
      </footer>

      {previewTemplate && (
        <TemplatePreviewModal
          template={previewTemplate}
          professionSlug={profession?.slug ?? ""}
          onClose={() => setPreviewTemplate(null)}
          onSelect={() => {
            setTemplateId(previewTemplate.id);
            setPreviewTemplate(null);
            setStep("form");
          }}
        />
      )}
    </div>
  );
}

function TemplatePreviewModal({
  template,
  professionSlug,
  onClose,
  onSelect,
}: {
  template: Template;
  professionSlug: string;
  onClose: () => void;
  onSelect: () => void;
}) {
  const previewImage =
    TEMPLATE_PREVIEW_IMAGE[`${professionSlug}:${template.slug}`] ?? template.preview_image_url;

  return (
    <div
      className="fixed inset-0 z-50 flex flex-col bg-black/70 p-4 sm:items-center sm:justify-center sm:p-8"
      onClick={onClose}
    >
      <div
        className="mx-auto flex w-full max-w-2xl flex-1 flex-col overflow-hidden rounded-2xl bg-white sm:flex-none"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="flex items-center justify-between border-b border-border-subtle px-4 py-3">
          <span className="text-sm font-semibold text-navy">{template.name}</span>
          <button
            onClick={onClose}
            aria-label="Cerrar"
            className="flex h-9 w-9 items-center justify-center rounded-full text-gray-500 transition-colors hover:bg-surface-muted hover:text-navy"
          >
            ✕
          </button>
        </div>

        <div className="flex-1 overflow-y-auto bg-surface-muted">
          {previewImage ? (
            // eslint-disable-next-line @next/next/no-img-element
            <img
              src={previewImage}
              alt={`Vista ampliada del diseño ${template.name}`}
              className="block w-full h-auto"
            />
          ) : (
            <div className="flex h-64 items-center justify-center text-sm font-medium text-gray-400">
              {template.name}
            </div>
          )}
        </div>

        <div className="flex justify-end gap-3 border-t border-border-subtle px-4 py-3">
          <button onClick={onClose} className={SECONDARY_BUTTON}>
            Cerrar
          </button>
          <button onClick={onSelect} className={PRIMARY_BUTTON}>
            Elegir este diseño
          </button>
        </div>
      </div>
    </div>
  );
}

function WizardHeader() {
  return (
    <header className="sticky top-0 z-30 border-b border-border-subtle bg-white/95 px-5 py-4 backdrop-blur sm:px-6">
      <Wordmark className="text-lg" />
    </header>
  );
}

function Steps({ current, subtle = false }: { current: Step; subtle?: boolean }) {
  const steps: { key: Step; label: string }[] = [
    { key: "profession", label: "Profesión" },
    { key: "template", label: "Plantilla" },
    { key: "form", label: "Datos" },
    { key: "slug", label: "Subdominio" },
  ];
  const currentIndex = steps.findIndex((s) => s.key === current);

  return (
    <ol className={`flex w-full items-start ${subtle ? "opacity-50" : ""}`}>
      {steps.map((s, i) => {
        const isActive = i === currentIndex;
        return (
          <li key={s.key} className="flex flex-1 flex-col items-center">
            <div className="flex w-full items-center">
              <div
                className={`flex shrink-0 items-center justify-center rounded-full font-semibold ${
                  subtle ? "h-6 w-6 text-xs" : "h-8 w-8 text-sm"
                } ${
                  isActive ? "bg-navy text-white" : "bg-gray-200 text-gray-400"
                }`}
              >
                {i + 1}
              </div>
              {i < steps.length - 1 && (
                <div className="mx-2 h-px flex-1 bg-gray-200" />
              )}
            </div>
            <span
              className={`mt-1.5 ${subtle ? "text-[10px]" : "mt-2 text-xs"} ${
                isActive ? "font-bold text-navy" : "text-gray-300"
              }`}
            >
              {s.label}
            </span>
          </li>
        );
      })}
    </ol>
  );
}

function TemplateCard({
  template,
  professionSlug,
  selected,
  onSelect,
  onPreview,
}: {
  template: Template;
  professionSlug: string;
  selected: boolean;
  onSelect: () => void;
  onPreview: () => void;
}) {
  const previewImage = TEMPLATE_PREVIEW_IMAGE[`${professionSlug}:${template.slug}`];

  return (
    <div
      role="button"
      tabIndex={0}
      aria-pressed={selected}
      aria-label={`Elegir plantilla ${template.name}`}
      onClick={onSelect}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onSelect();
        }
      }}
      className={`group flex cursor-pointer flex-col gap-0 transition-all duration-200 hover:-translate-y-1 focus-visible:outline-none ${
        selected ? "opacity-100" : ""
      }`}
    >
      {/* imagen del template — ancho completo sin recorte */}
      <div
        className={`relative w-full overflow-hidden rounded-2xl bg-white transition-shadow duration-200 ${
          selected
            ? "ring-[3px] ring-sky shadow-lg shadow-sky/20"
            : "ring-1 ring-black/8 group-hover:shadow-md group-hover:ring-black/15"
        }`}
      >
        {previewImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={previewImage}
            alt={`Vista previa del diseño ${template.name}`}
            className="block w-full h-auto"
          />
        ) : template.preview_image_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={template.preview_image_url}
            alt={template.name}
            className="block w-full h-auto"
          />
        ) : (
          <div className="flex h-48 items-center justify-center text-sm font-medium text-gray-400">
            {template.name}
          </div>
        )}

        {/* overlay hover */}
        <div className="absolute inset-0 flex flex-col items-center justify-end gap-2 bg-gradient-to-t from-navy/70 via-transparent to-transparent pb-5 opacity-0 transition-opacity duration-200 group-hover:opacity-100 group-focus-visible:opacity-100">
          <span className="rounded-full bg-white px-5 py-2 text-sm font-semibold text-navy shadow-sm">
            Elegir este diseño
          </span>
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onPreview();
            }}
            className="rounded-full border border-white/70 px-4 py-1.5 text-xs font-semibold text-white transition-colors hover:bg-white/10"
          >
            Ver en grande
          </button>
        </div>

        {/* check si está seleccionado */}
        {selected && (
          <div className="absolute right-3 top-3 flex h-7 w-7 items-center justify-center rounded-full bg-sky text-white shadow-md">
            <svg viewBox="0 0 20 20" fill="none" className="h-4 w-4">
              <path
                d="M4 10.5l3.5 3.5L16 5.5"
                stroke="currentColor"
                strokeWidth="2.2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
        )}
      </div>

      {/* nombre del template abajo */}
      <div className="flex items-center justify-between px-1 pt-3">
        <span className={`text-sm font-semibold ${selected ? "text-sky" : "text-gray-800"}`}>
          {template.name}
        </span>
        {selected && (
          <span className="text-xs font-medium text-sky">Seleccionado</span>
        )}
      </div>
    </div>
  );
}

function SlugFeedback({
  status,
  onPick,
}: {
  status: SlugStatus;
  onPick: (slug: string) => void;
}) {
  if (status.state === "checking") {
    return (
      <p className="text-sm text-text-body">Comprobando disponibilidad...</p>
    );
  }
  if (status.state === "available") {
    return <p className="text-sm text-green-600">Disponible ✓</p>;
  }
  if (status.state === "invalid") {
    return <p className="text-sm text-red-600">{status.message}</p>;
  }
  return (
    <div className="text-sm text-red-600">
      <p>Ese subdominio ya está en uso. Alternativas:</p>
      <div className="mt-2 flex flex-wrap gap-2">
        {status.suggestions.map((s) => (
          <button
            key={s}
            onClick={() => onPick(s)}
            className="min-h-9 rounded-full border border-border-subtle px-3 text-navy"
          >
            {s}
          </button>
        ))}
      </div>
    </div>
  );
}
