"use client";

import { useEffect, useMemo, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import type { FormSchema } from "@/lib/forms/validate-form-data";
import { ROOT_DOMAIN } from "@/lib/root-domain";
import { FieldInput } from "@/components/forms/FieldInput";
import { Wordmark } from "@/components/landing/Wordmark";
import { checkSlugAvailabilityAction, createLandingAction } from "./actions";
import { ContadorWizard } from "./ContadorWizard";
import { AbogadoWizard } from "./AbogadoWizard";
import { PRIMARY_BUTTON, SECONDARY_BUTTON } from "./styles";

export interface Profession {
  id: string;
  name: string;
  slug: string;
  form_schema: FormSchema;
}

export interface Template {
  id: string;
  profession_id: string;
  name: string;
  slug: string;
  preview_image_url: string | null;
  config: {
    primaryColor?: string;
    secondaryColor?: string;
    layout?: string;
  } | null;
}

export interface StockImage {
  id: string;
  category: string;
  image_url: string;
}

type Step = "profession" | "template" | "form" | "slug";

type SlugStatus =
  | { state: "checking" }
  | { state: "available" }
  | { state: "taken"; suggestions: string[] }
  | { state: "invalid"; message: string };

// Professions with a dedicated, richer wizard (own steps + live preview)
// instead of the generic form_schema-driven fallback below. The grid in
// the "profession" step still renders every row from the DB; the branch
// right below this set picks which wizard component to render for each.
const DEDICATED_WIZARD_PROFESSIONS = new Set(["contadores", "abogados"]);

// Static preview thumbnails for the templates that were ported to React.
// Most are generated by `npm run generate:previews`
// (scripts/generate-previews.js), which fills each template's
// {{placeholders}} with fictional sample data, renders it with Playwright,
// and writes a JPEG (public/previews/) shown as the full card image below.
// The contador clasico/minimal ones were instead captured directly from the
// real live-preview wizard (Playwright screenshotting the actual
// ContadorClasicoTemplate/ContadorMinimalTemplate component with sample
// data) since they have no separate static-HTML source under /templates/ --
// see the one-off script this shipped with. Templates without an entry
// here fall back to a plain name-only card.
const TEMPLATE_PREVIEW_IMAGE: Record<string, string> = {
  "contadores:moderno": "/previews/contador-moderno.jpg",
  "contadores:clasico": "/previews/contador-clasico.jpg",
  "contadores:minimal": "/previews/contador-minimal.jpg",
  "abogados:moderno": "/previews/abogado-moderno.jpg",
  "abogados:clasico": "/previews/abogado-clasico.jpg",
  "abogados:minimal": "/previews/abogado-minimal.jpg",
};

// For the "profession" step card, one representative screenshot per
// profession (its flagship "Moderno" template) rather than a generic
// icon -- reuses the same real Playwright-rendered images above instead
// of a placeholder gradient, for the professions that have one.
const PROFESSION_PREVIEW_IMAGE: Record<string, string> = {
  contadores: "/previews/contador-moderno.jpg",
  abogados: "/previews/abogado-moderno.jpg",
};

// Fallback for a profession with no rendered preview yet.
const PROFESSION_GRADIENT: Record<string, string> = {
  contadores: "linear-gradient(135deg, #0B2545, #1A6B4A)",
  abogados: "linear-gradient(135deg, #1C1C2E, #C9A84C)",
};

const PROFESSION_SUBTITLE: Record<string, string> = {
  contadores: "Impuestos · Liquidaciones · Asesoramiento",
  abogados: "Derecho Civil · Familia · Societario · Laboral",
};

export function OnboardingWizard({
  professions,
  templates,
  stockImages,
  isAuthenticated,
}: {
  professions: Profession[];
  templates: Template[];
  stockImages: StockImage[];
  isAuthenticated: boolean;
}) {
  const router = useRouter();
  const [step, setStep] = useState<Step>("profession");
  const [professionId, setProfessionId] = useState<string | null>(null);
  const [templateId, setTemplateId] = useState<string | null>(null);
  const [values, setValues] = useState<Record<string, string>>({});
  const [imageMode, setImageMode] = useState<"stock" | "manual">("stock");
  const [slugInput, setSlugInput] = useState("");
  const [slugStatus, setSlugStatus] = useState<SlugStatus | null>(null);
  const [formErrors, setFormErrors] = useState<Record<string, string>>({});
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [isPending, startTransition] = useTransition();

  const profession = professions.find((p) => p.id === professionId) ?? null;
  const professionTemplates = useMemo(
    () => templates.filter((t) => t.profession_id === professionId),
    [templates, professionId]
  );
  const selectedTemplate =
    professionTemplates.find((t) => t.id === templateId) ?? null;
  const usesDedicatedWizard = Boolean(
    profession && DEDICATED_WIZARD_PROFESSIONS.has(profession.slug)
  );

  useEffect(() => {
    if (step !== "slug" || slugInput.trim().length === 0) {
      return;
    }
    const handle = setTimeout(async () => {
      setSlugStatus({ state: "checking" });
      const result = await checkSlugAvailabilityAction(slugInput);
      if (!result.valid) {
        setSlugStatus({ state: "invalid", message: result.message });
      } else if (result.available) {
        setSlugStatus({ state: "available" });
      } else {
        setSlugStatus({ state: "taken", suggestions: result.suggestions });
      }
    }, 500);
    return () => clearTimeout(handle);
  }, [slugInput, step]);

  function updateValue(key: string, value: string) {
    setValues((v) => ({ ...v, [key]: value }));
  }

  function handleSubmit() {
    if (!professionId || !templateId) return;
    setSubmitError(null);
    setFormErrors({});
    startTransition(async () => {
      const result = await createLandingAction({
        professionId,
        templateId,
        formData: values,
        desiredSlug: slugInput,
      });

      if (result.ok) {
        router.push("/dashboard");
        return;
      }

      switch (result.reason) {
        case "invalid_form_data":
          setFormErrors(result.errors);
          setStep("form");
          break;
        case "slug_taken":
          setSlugStatus({ state: "taken", suggestions: result.suggestions });
          break;
        case "invalid_slug":
          setSlugStatus({ state: "invalid", message: result.message });
          break;
        case "already_has_landing":
          router.push("/dashboard");
          break;
        default:
          setSubmitError("No se pudo crear la landing. Intentá de nuevo.");
      }
    });
  }

  return (
    <div className="flex min-h-full flex-1 flex-col bg-[#f8fafc]">
      <WizardHeader />

      {step === "form" && profession && usesDedicatedWizard && selectedTemplate ? (
        profession.slug === "abogados" ? (
          <AbogadoWizard
            profession={profession}
            template={selectedTemplate}
            stockImages={stockImages}
            isAuthenticated={isAuthenticated}
            onBack={() => setStep("template")}
          />
        ) : (
          <ContadorWizard
            profession={profession}
            template={selectedTemplate}
            stockImages={stockImages}
            isAuthenticated={isAuthenticated}
            onBack={() => setStep("template")}
          />
        )
      ) : (
        <div className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-16 px-8 py-16">
          {(step === "form" || step === "slug") && <Steps current={step} />}

          {step === "profession" && (
            <section className="flex flex-col gap-8">
              <div className="flex flex-col gap-2">
                <h2 className="text-3xl font-bold text-navy">
                  Elegí tu profesión
                </h2>
                <p className="text-base text-gray-500">
                  Seleccioná tu área profesional para ver las plantillas
                  disponibles.
                </p>
              </div>

              <div className="flex justify-center">
                <div className="w-full max-w-sm">
                  <Steps current="profession" subtle />
                </div>
              </div>

              <div className="grid gap-6 sm:grid-cols-3">
                {professions.map((p) => {
                  const previewImage = PROFESSION_PREVIEW_IMAGE[p.slug];
                  const gradient =
                    PROFESSION_GRADIENT[p.slug] ??
                    "linear-gradient(135deg, #0f1f3d, #334155)";
                  const subtitle =
                    PROFESSION_SUBTITLE[p.slug] ??
                    "Plantillas profesionales listas para usar";

                  return (
                    <button
                      key={p.id}
                      onClick={() => {
                        setProfessionId(p.id);
                        setTemplateId(null);
                        setStep("template");
                      }}
                      className="group relative flex flex-col overflow-hidden rounded-2xl bg-white text-left shadow-sm ring-1 ring-black/5 transition-all duration-200 hover:-translate-y-1 hover:shadow-lg"
                    >
                      {/* imagen fija — siempre 220 px, recortada desde arriba */}
                      <div className="relative h-[220px] w-full shrink-0 overflow-hidden">
                        {previewImage ? (
                          <Image
                            src={previewImage}
                            alt={`Vista previa de páginas de ${p.name}`}
                            fill
                            sizes="(min-width: 640px) 33vw, 100vw"
                            className="object-cover object-top"
                          />
                        ) : (
                          <div
                            className="flex h-full w-full items-center justify-center"
                            style={{ background: gradient }}
                          >
                            <span className="text-sm font-medium text-white/90">
                              Moderno · Clásico · Minimal
                            </span>
                          </div>
                        )}
                      </div>

                      {/* info — altura fija para que todas las cards sean iguales */}
                      <div className="flex min-h-[88px] flex-col justify-center gap-1 px-5 py-4">
                        <span className="text-lg font-semibold text-gray-900 leading-snug">
                          {p.name}
                        </span>
                        <span className="text-xs text-gray-400 leading-relaxed">
                          {subtitle}
                        </span>
                      </div>

                      <div className="pointer-events-none absolute inset-x-0 bottom-0 flex h-11 items-center justify-center bg-navy text-sm font-medium text-white opacity-0 transition-opacity duration-200 group-hover:opacity-100">
                        Comenzar →
                      </div>
                    </button>
                  );
                })}

                {/* Psicólogos — próximamente */}
                <div className="relative flex flex-col overflow-hidden rounded-2xl bg-white ring-1 ring-black/5 opacity-55 cursor-not-allowed select-none">
                  <div className="relative h-[220px] w-full shrink-0 overflow-hidden">
                    <div
                      className="flex h-full w-full items-center justify-center"
                      style={{ background: "linear-gradient(135deg, #4A5568, #A0AEC0)" }}
                    >
                      <span className="rounded-full bg-white/25 px-4 py-1.5 text-xs font-semibold tracking-wide text-white uppercase">
                        Próximamente
                      </span>
                    </div>
                  </div>
                  <div className="flex min-h-[88px] flex-col justify-center gap-1 px-5 py-4">
                    <span className="text-lg font-semibold text-gray-900 leading-snug">Psicólogos</span>
                    <span className="text-xs text-gray-400 leading-relaxed">Clínica · Infanto-juvenil · Organizacional</span>
                  </div>
                </div>
              </div>

              <Link
                href="/"
                className="pt-2 text-center text-sm text-sky hover:underline"
              >
                También podés ver ejemplos de páginas terminadas antes de
                empezar →
              </Link>
            </section>
          )}

          {step === "template" && profession && (
            <section className="flex flex-col gap-8">
              <div className="flex flex-col gap-1">
                <h2 className="text-3xl font-bold text-navy">Elegí tu diseño</h2>
                <p className="text-base text-gray-500">
                  Todos los diseños incluyen las mismas secciones. Podés cambiar el estilo después.
                </p>
              </div>

              <div className="flex justify-center">
                <div className="w-full max-w-sm">
                  <Steps current="template" subtle />
                </div>
              </div>

              <div className="grid gap-6 sm:grid-cols-3">
                {professionTemplates.map((t) => (
                  <TemplateCard
                    key={t.id}
                    template={t}
                    professionSlug={profession.slug}
                    selected={templateId === t.id}
                    onSelect={() => {
                      setTemplateId(t.id);
                      setStep("form");
                    }}
                  />
                ))}
              </div>

              <button
                onClick={() => setStep("profession")}
                className="self-start text-sm text-gray-400 hover:text-navy hover:underline"
              >
                ← Volver a profesiones
              </button>
            </section>
          )}

          {step === "form" && profession && (
            <section className="flex flex-col gap-4">
              <h2 className="text-xl font-semibold text-navy">
                Completá tus datos
              </h2>
              {profession.form_schema.fields.map((field) => (
                <FieldInput
                  key={field.key}
                  field={field}
                  value={values[field.key] ?? ""}
                  error={formErrors[field.key]}
                  onChange={(v) =>
                    updateValue(field.key, typeof v === "string" ? v : "")
                  }
                  imageMode={imageMode}
                  onImageModeChange={setImageMode}
                  stockImages={stockImages}
                />
              ))}
              {formErrors._form && (
                <p className="text-sm text-red-600">{formErrors._form}</p>
              )}
              <div className="flex gap-3">
                <button onClick={() => setStep("template")} className={SECONDARY_BUTTON}>
                  Volver
                </button>
                <button onClick={() => setStep("slug")} className={PRIMARY_BUTTON}>
                  Continuar
                </button>
              </div>
            </section>
          )}

          {step === "slug" && (
            <section className="flex flex-col gap-4">
              <h2 className="text-xl font-semibold text-navy">
                Elegí tu subdominio
              </h2>
              <div className="flex items-center gap-2">
                <input
                  value={slugInput}
                  onChange={(e) => setSlugInput(e.target.value)}
                  placeholder="ej: contadorjuanperez"
                  className="min-h-12 flex-1 rounded-lg border border-border-subtle bg-white px-3 py-2 text-navy focus:border-sky focus:outline-none focus:ring-2 focus:ring-sky/30"
                />
                <span className="text-sm text-text-body">.{ROOT_DOMAIN}</span>
              </div>

              {slugStatus && (
                <SlugFeedback status={slugStatus} onPick={setSlugInput} />
              )}

              {submitError && (
                <p className="text-sm text-red-600">{submitError}</p>
              )}

              <div className="flex gap-3">
                <button onClick={() => setStep("form")} className={SECONDARY_BUTTON}>
                  Volver
                </button>
                <button
                  onClick={handleSubmit}
                  disabled={isPending || slugStatus?.state !== "available"}
                  className={PRIMARY_BUTTON}
                >
                  {isPending ? "Creando..." : "Crear landing"}
                </button>
              </div>
            </section>
          )}
        </div>
      )}
      <footer className="mt-auto border-t border-gray-100 px-6 py-5 text-center text-xs text-gray-400">
        <span>© {new Date().getFullYear()} weboficial</span>
        {" · "}
        <a href="/terminos" className="hover:text-gray-600 hover:underline">Términos</a>
        {" · "}
        <a href="/privacidad" className="hover:text-gray-600 hover:underline">Privacidad</a>
        {" · "}
        <a href="mailto:ideasdigitalesml@gmail.com" className="hover:text-gray-600 hover:underline">Contacto</a>
      </footer>
    </div>
  );
}

function WizardHeader() {
  return (
    <header className="border-b border-border-subtle px-6 py-4">
      <Wordmark className="text-lg" />
    </header>
  );
}

function Steps({ current, subtle = false }: { current: Step; subtle?: boolean }) {
  const steps: { key: Step; label: string }[] = [
    { key: "profession", label: "Profesión" },
    { key: "template", label: "Plantilla" },
    { key: "form", label: "Datos" },
    { key: "slug", label: "Subdominio" },
  ];
  const currentIndex = steps.findIndex((s) => s.key === current);

  return (
    <ol className={`flex w-full items-start ${subtle ? "opacity-50" : ""}`}>
      {steps.map((s, i) => {
        const isActive = i === currentIndex;
        return (
          <li key={s.key} className="flex flex-1 flex-col items-center">
            <div className="flex w-full items-center">
              <div
                className={`flex shrink-0 items-center justify-center rounded-full font-semibold ${
                  subtle ? "h-6 w-6 text-xs" : "h-8 w-8 text-sm"
                } ${
                  isActive ? "bg-navy text-white" : "bg-gray-200 text-gray-400"
                }`}
              >
                {i + 1}
              </div>
              {i < steps.length - 1 && (
                <div className="mx-2 h-px flex-1 bg-gray-200" />
              )}
            </div>
            <span
              className={`mt-1.5 ${subtle ? "text-[10px]" : "mt-2 text-xs"} ${
                isActive ? "font-bold text-navy" : "text-gray-300"
              }`}
            >
              {s.label}
            </span>
          </li>
        );
      })}
    </ol>
  );
}

function TemplateCard({
  template,
  professionSlug,
  selected,
  onSelect,
}: {
  template: Template;
  professionSlug: string;
  selected: boolean;
  onSelect: () => void;
}) {
  const previewImage = TEMPLATE_PREVIEW_IMAGE[`${professionSlug}:${template.slug}`];

  return (
    <div
      role="button"
      tabIndex={0}
      aria-pressed={selected}
      aria-label={`Elegir plantilla ${template.name}`}
      onClick={onSelect}
      onKeyDown={(e) => {
        if (e.key === "Enter" || e.key === " ") {
          e.preventDefault();
          onSelect();
        }
      }}
      className={`group flex cursor-pointer flex-col gap-0 transition-all duration-200 hover:-translate-y-1 focus-visible:outline-none ${
        selected ? "opacity-100" : ""
      }`}
    >
      {/* imagen del template — ancho completo sin recorte */}
      <div
        className={`relative w-full overflow-hidden rounded-2xl bg-white transition-shadow duration-200 ${
          selected
            ? "ring-[3px] ring-sky shadow-lg shadow-sky/20"
            : "ring-1 ring-black/8 group-hover:shadow-md group-hover:ring-black/15"
        }`}
      >
        {previewImage ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={previewImage}
            alt={`Vista previa del diseño ${template.name}`}
            className="block w-full h-auto"
          />
        ) : template.preview_image_url ? (
          // eslint-disable-next-line @next/next/no-img-element
          <img
            src={template.preview_image_url}
            alt={template.name}
            className="block w-full h-auto"
          />
        ) : (
          <div className="flex h-48 items-center justify-center text-sm font-medium text-gray-400">
            {template.name}
          </div>
        )}

        {/* overlay hover */}
        <div className="absolute inset-0 flex items-end justify-center bg-gradient-to-t from-navy/70 via-transparent to-transparent pb-5 opacity-0 transition-opacity duration-200 group-hover:opacity-100 group-focus-visible:opacity-100">
          <span className="rounded-full bg-white px-5 py-2 text-sm font-semibold text-navy shadow-sm">
            Elegir este diseño
          </span>
        </div>

        {/* check si está seleccionado */}
        {selected && (
          <div className="absolute right-3 top-3 flex h-7 w-7 items-center justify-center rounded-full bg-sky text-white shadow-md">
            <svg viewBox="0 0 20 20" fill="none" className="h-4 w-4">
              <path
                d="M4 10.5l3.5 3.5L16 5.5"
                stroke="currentColor"
                strokeWidth="2.2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </div>
        )}
      </div>

      {/* nombre del template abajo */}
      <div className="flex items-center justify-between px-1 pt-3">
        <span className={`text-sm font-semibold ${selected ? "text-sky" : "text-gray-800"}`}>
          {template.name}
        </span>
        {selected && (
          <span className="text-xs font-medium text-sky">Seleccionado</span>
        )}
      </div>
    </div>
  );
}

function SlugFeedback({
  status,
  onPick,
}: {
  status: SlugStatus;
  onPick: (slug: string) => void;
}) {
  if (status.state === "checking") {
    return (
      <p className="text-sm text-text-body">Comprobando disponibilidad...</p>
    );
  }
  if (status.state === "available") {
    return <p className="text-sm text-green-600">Disponible ✓</p>;
  }
  if (status.state === "invalid") {
    return <p className="text-sm text-red-600">{status.message}</p>;
  }
  return (
    <div className="text-sm text-red-600">
      <p>Ese subdominio ya está en uso. Alternativas:</p>
      <div className="mt-2 flex flex-wrap gap-2">
        {status.suggestions.map((s) => (
          <button
            key={s}
            onClick={() => onPick(s)}
            className="min-h-9 rounded-full border border-border-subtle px-3 text-navy"
          >
            {s}
          </button>
        ))}
      </div>
    </div>
  );
}
